#![forbid(unsafe_code)]

pub mod assignee;
mod auth;

mod actor;
mod agent_chats;
mod analytics;
mod coordination;
mod core;
mod daemon_transport;
mod execution;
mod git;
mod integration;
mod lists;
mod mcp;
mod memory;
mod mission_control;
mod oauth;
mod operations;
mod product_genesis;
mod project_hooks;
mod project_orchestration;
mod provider_auth;
mod repo_review;
mod requests;
mod runtime;
mod settings;
mod terminal;
mod workflow;

pub use actor::*;
pub use agent_chats::*;
pub use analytics::*;
pub use auth::*;
pub use coordination::*;
pub use core::*;
pub use daemon_transport::*;
pub use execution::*;
pub use git::*;
pub use integration::*;
pub use lists::*;
pub use mcp::*;
pub use memory::*;
pub use mission_control::*;
pub use oauth::*;
pub use operations::*;
pub use product_genesis::*;
pub use project_hooks::*;
pub use project_orchestration::*;
pub use provider_auth::*;
pub use repo_review::*;
pub use requests::*;
pub use runtime::*;
pub use settings::*;
pub use terminal::*;
pub use workflow::*;

#[test]
#[ignore = "manual type export for the web client"]
fn export_typescript() {
    use ts_rs::TS;

    let out_dir =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../web/src/types/generated");
    std::fs::create_dir_all(&out_dir).expect("create types output directory");
    std::env::set_current_dir(&out_dir).expect("switch to types output directory");

    TaskType::export().expect("export TaskType");
    ProductMaturity::export().expect("export ProductMaturity");
    ProductGenesisLifecycle::export().expect("export ProductGenesisLifecycle");
    ProductGenesisSession::export().expect("export ProductGenesisSession");
    StartProductGenesisRequest::export().expect("export StartProductGenesisRequest");
    ProductGenesisStartResponse::export().expect("export ProductGenesisStartResponse");
    ProductGenesisActiveResponse::export().expect("export ProductGenesisActiveResponse");
    CancelProductGenesisRequest::export().expect("export CancelProductGenesisRequest");
    WorkMode::export().expect("export WorkMode");
    CreateRepoRequest::export().expect("export CreateRepoRequest");
    UpdateRepoRequest::export().expect("export UpdateRepoRequest");
    RepoResponse::export().expect("export RepoResponse");
    RepoSyncResponse::export().expect("export RepoSyncResponse");
    FsEntry::export().expect("export FsEntry");
    FsListResponse::export().expect("export FsListResponse");
    BranchListResponse::export().expect("export BranchListResponse");
    ReviewConfig::export().expect("export ReviewConfig");
    RetryBudgets::export().expect("export RetryBudgets");
    AutomaticRecoverySettings::export().expect("export AutomaticRecoverySettings");
    LifecycleEvent::export().expect("export LifecycleEvent");
    LifecycleHookDef::export().expect("export LifecycleHookDef");
    ProjectSettings::export().expect("export ProjectSettings");
    LifecycleHookTestResponse::export().expect("export LifecycleHookTestResponse");
    TaskMetadata::export().expect("export TaskMetadata");
    Task::export().expect("export Task");
    TaskAction::export().expect("export TaskAction");
    TaskActionsResponse::export().expect("export TaskActionsResponse");
    StopReason::export().expect("export StopReason");
    ResumePolicy::export().expect("export ResumePolicy");
    RecoveryAction::export().expect("export RecoveryAction");
    ExecutionBehaviorKind::export().expect("export ExecutionBehaviorKind");
    ExecutionBehavior::export().expect("export ExecutionBehavior");
    ExecutionActionKind::export().expect("export ExecutionActionKind");
    ExecutionAction::export().expect("export ExecutionAction");
    BlockingArtifact::export().expect("export BlockingArtifact");
    TaskBlockingAnnotation::export().expect("export TaskBlockingAnnotation");
    InterruptionMetadata::export().expect("export InterruptionMetadata");
    TaskAnnotation::export().expect("export TaskAnnotation");
    TaskExecutionObservability::export().expect("export TaskExecutionObservability");
    TaskResponse::export().expect("export TaskResponse");
    ExecutionUsageResponse::export().expect("export ExecutionUsageResponse");
    TaskUsageSummaryResponse::export().expect("export TaskUsageSummaryResponse");
    PromptPreviewResponse::export().expect("export PromptPreviewResponse");
    MemorySearchQuery::export().expect("export MemorySearchQuery");
    MemoryGetQuery::export().expect("export MemoryGetQuery");
    MemorySearchResultDto::export().expect("export MemorySearchResultDto");
    MemorySearchResponse::export().expect("export MemorySearchResponse");
    MemoryPublicationRequest::export().expect("export MemoryPublicationRequest");
    MemoryLifecycleRequest::export().expect("export MemoryLifecycleRequest");
    MemoryLifecycleResponse::export().expect("export MemoryLifecycleResponse");
    MemoryProvenanceResponse::export().expect("export MemoryProvenanceResponse");
    ContextManifestQuery::export().expect("export ContextManifestQuery");
    ContextManifestListQuery::export().expect("export ContextManifestListQuery");
    ContextManifestSourceResponse::export().expect("export ContextManifestSourceResponse");
    ContextManifestResponse::export().expect("export ContextManifestResponse");
    ContextManifestListResponse::export().expect("export ContextManifestListResponse");
    MemoryProvenanceQuery::export().expect("export MemoryProvenanceQuery");
    AttentionLifecycle::export().expect("export AttentionLifecycle");
    AttentionCategory::export().expect("export AttentionCategory");
    AttentionItem::export().expect("export AttentionItem");
    AttentionListResponse::export().expect("export AttentionListResponse");
    AttentionConsumerHealthResponse::export().expect("export AttentionConsumerHealthResponse");
    AttentionMutationRequest::export().expect("export AttentionMutationRequest");
    AttentionSnoozeRequest::export().expect("export AttentionSnoozeRequest");
    MissionControlWorkItem::export().expect("export MissionControlWorkItem");
    MissionControlAgentHealth::export().expect("export MissionControlAgentHealth");
    MissionControlRecentOutcome::export().expect("export MissionControlRecentOutcome");
    MissionControlCapacity::export().expect("export MissionControlCapacity");
    MissionControlHomeResponse::export().expect("export MissionControlHomeResponse");
    MissionControlQuery::export().expect("export MissionControlQuery");
    AgentDetailResponse::export().expect("export AgentDetailResponse");
    AgentBindingSummary::export().expect("export AgentBindingSummary");
    AgentUsageSummary::export().expect("export AgentUsageSummary");
    AgentScopeSummary::export().expect("export AgentScopeSummary");
    AgentSessionSummary::export().expect("export AgentSessionSummary");
    AgentContinuityHealth::export().expect("export AgentContinuityHealth");
    TerminalSessionStatus::export().expect("export TerminalSessionStatus");
    TerminalSessionResponse::export().expect("export TerminalSessionResponse");
    CreateTerminalSessionRequest::export().expect("export CreateTerminalSessionRequest");
    ResizeTerminalSessionRequest::export().expect("export ResizeTerminalSessionRequest");
    TerminalAttachTokenResponse::export().expect("export TerminalAttachTokenResponse");
    TerminalAvailability::export().expect("export TerminalAvailability");
    TerminalClientFrame::export().expect("export TerminalClientFrame");
    TerminalServerFrame::export().expect("export TerminalServerFrame");
    TasksResponse::export().expect("export TasksResponse");
    MoveTaskRequest::export().expect("export MoveTaskRequest");
    MoveTaskResponse::export().expect("export MoveTaskResponse");
    OperationConflictDetails::export().expect("export OperationConflictDetails");
    TaskVersionConflictDetails::export().expect("export TaskVersionConflictDetails");
    BoardRevisionConflictDetails::export().expect("export BoardRevisionConflictDetails");
    TaskMovedEventPayload::export().expect("export TaskMovedEventPayload");
    Agent::export().expect("export Agent");
    AgentStatus::export().expect("export AgentStatus");
    AgentResponse::export().expect("export AgentResponse");
    AgentsResponse::export().expect("export AgentsResponse");
    Project::export().expect("export Project");
    ProjectHookRule::export().expect("export ProjectHookRule");
    ProjectHookTrigger::export().expect("export ProjectHookTrigger");
    ProjectHookAction::export().expect("export ProjectHookAction");
    ProjectHookRunStatus::export().expect("export ProjectHookRunStatus");
    ProjectHookRunResponse::export().expect("export ProjectHookRunResponse");
    ProjectHookRunsResponse::export().expect("export ProjectHookRunsResponse");
    ProjectsResponse::export().expect("export ProjectsResponse");
    AgentBindingState::export().expect("export AgentBindingState");
    AgentChatKind::export().expect("export AgentChatKind");
    AgentChatStatus::export().expect("export AgentChatStatus");
    AgentChatMessageAuthorType::export().expect("export AgentChatMessageAuthorType");
    AgentChatMessageStatus::export().expect("export AgentChatMessageStatus");
    AgentChatTurnStatus::export().expect("export AgentChatTurnStatus");
    AgentHandoffStatus::export().expect("export AgentHandoffStatus");
    MainAgentBindingResponse::export().expect("export MainAgentBindingResponse");
    ProjectAgentBindingResponse::export().expect("export ProjectAgentBindingResponse");
    SetMainAgentBindingRequest::export().expect("export SetMainAgentBindingRequest");
    SetProjectAgentBindingRequest::export().expect("export SetProjectAgentBindingRequest");
    AgentChatResponse::export().expect("export AgentChatResponse");
    AgentChatDetailResponse::export().expect("export AgentChatDetailResponse");
    AgentChatSwitcherItem::export().expect("export AgentChatSwitcherItem");
    AgentChatSwitcherResponse::export().expect("export AgentChatSwitcherResponse");
    AgentChatMessageResponse::export().expect("export AgentChatMessageResponse");
    AgentChatTurnJobResponse::export().expect("export AgentChatTurnJobResponse");
    SendAgentChatMessageRequest::export().expect("export SendAgentChatMessageRequest");
    SendAgentChatMessageResponse::export().expect("export SendAgentChatMessageResponse");
    CancelAgentChatTurnRequest::export().expect("export CancelAgentChatTurnRequest");
    CreateAgentHandoffRequest::export().expect("export CreateAgentHandoffRequest");
    AgentHandoffResponse::export().expect("export AgentHandoffResponse");
    AgentChatListQuery::export().expect("export AgentChatListQuery");
    AgentChatListResponse::export().expect("export AgentChatListResponse");
    AgentChatMessagesQuery::export().expect("export AgentChatMessagesQuery");
    AgentChatMessageListResponse::export().expect("export AgentChatMessageListResponse");
    CreateEmbeddedAgentRequest::export().expect("export CreateEmbeddedAgentRequest");
    ConnectEmbeddedProfileRequest::export().expect("export ConnectEmbeddedProfileRequest");
    CanonicalScopeRequest::export().expect("export CanonicalScopeRequest");
    CreateAgentSessionRequest::export().expect("export CreateAgentSessionRequest");
    SessionVersionRequest::export().expect("export SessionVersionRequest");
    SteerAgentSessionRequest::export().expect("export SteerAgentSessionRequest");
    CredentialHandleResponse::export().expect("export CredentialHandleResponse");
    ProviderRevocationStatus::export().expect("export ProviderRevocationStatus");
    DisconnectCredentialResponse::export().expect("export DisconnectCredentialResponse");
    AgentProfileResponse::export().expect("export AgentProfileResponse");
    AgentConnectionHealthResponse::export().expect("export AgentConnectionHealthResponse");
    AgentSessionResponse::export().expect("export AgentSessionResponse");
    ProtectedInteractionSummaryResponse::export()
        .expect("export ProtectedInteractionSummaryResponse");
    ProtectedInteractionAnswerRequest::export().expect("export ProtectedInteractionAnswerRequest");
    ProtectedInteractionAnswerValue::export().expect("export ProtectedInteractionAnswerValue");
    ProtectedInteractionCancelRequest::export().expect("export ProtectedInteractionCancelRequest");
    ConnectedEmbeddedAgentResponse::export().expect("export ConnectedEmbeddedAgentResponse");
    ConnectedEmbeddedProfileResponse::export().expect("export ConnectedEmbeddedProfileResponse");
    EffectivePermissionsResponse::export().expect("export EffectivePermissionsResponse");
    AgentProviderId::export().expect("export AgentProviderId");
    ProviderCredentialMethod::export().expect("export ProviderCredentialMethod");
    ProviderSupportLevel::export().expect("export ProviderSupportLevel");
    ProviderRuntimeCapability::export().expect("export ProviderRuntimeCapability");
    ProviderCredentialCapability::export().expect("export ProviderCredentialCapability");
    AgentProviderCapability::export().expect("export AgentProviderCapability");
    AgentProviderCapabilitiesResponse::export().expect("export AgentProviderCapabilitiesResponse");
    ProviderEntryAgentRef::export().expect("export ProviderEntryAgentRef");
    ProviderEntryResponse::export().expect("export ProviderEntryResponse");
    CliRuntimeEntryResponse::export().expect("export CliRuntimeEntryResponse");
    ProviderEntriesResponse::export().expect("export ProviderEntriesResponse");
    ProviderEntryTestResponse::export().expect("export ProviderEntryTestResponse");
    CreateProviderEntryRequest::export().expect("export CreateProviderEntryRequest");
    RenameProviderEntryRequest::export().expect("export RenameProviderEntryRequest");
    ProviderAuthorizationState::export().expect("export ProviderAuthorizationState");
    StartProviderAuthorizationRequest::export().expect("export StartProviderAuthorizationRequest");
    CancelProviderAuthorizationRequest::export()
        .expect("export CancelProviderAuthorizationRequest");
    ProviderAuthorizationOperationResponse::export()
        .expect("export ProviderAuthorizationOperationResponse");
    CommitmentResponse::export().expect("export CommitmentResponse");
    CreateCommitmentRequest::export().expect("export CreateCommitmentRequest");
    UpdateCommitmentRequest::export().expect("export UpdateCommitmentRequest");
    CompleteCommitmentRequest::export().expect("export CompleteCommitmentRequest");
    TransferCommitmentRequest::export().expect("export TransferCommitmentRequest");
    CommitmentEvidenceResponse::export().expect("export CommitmentEvidenceResponse");
    CoordinationListQuery::export().expect("export CoordinationListQuery");
    InboxItemResponse::export().expect("export InboxItemResponse");
    UpdateInboxItemRequest::export().expect("export UpdateInboxItemRequest");
    AskQuestionRequest::export().expect("export AskQuestionRequest");
    QuestionResponse::export().expect("export QuestionResponse");
    AnswerQuestionRequest::export().expect("export AnswerQuestionRequest");
    AgentActionResponse::export().expect("export AgentActionResponse");
    ProposeActionRequest::export().expect("export ProposeActionRequest");
    TaskProposalRequest::export().expect("export TaskProposalRequest");
    ApproveActionRequest::export().expect("export ApproveActionRequest");
    ExecuteActionRequest::export().expect("export ExecuteActionRequest");
    ExecuteOrchestrationActionRequest::export().expect("export ExecuteOrchestrationActionRequest");
    ExecuteTaskProposalRequest::export().expect("export ExecuteTaskProposalRequest");
    ActionExecutionResponse::export().expect("export ActionExecutionResponse");
    TaskProposalExecutionResponse::export().expect("export TaskProposalExecutionResponse");
    TaskGovernanceRequest::export().expect("export TaskGovernanceRequest");
    TransitionSource::export().expect("export TransitionSource");
    TransitionTaskRequest::export().expect("export TransitionTaskRequest");
    AuthorType::export().expect("export AuthorType");
    TaskMediaResponse::export().expect("export TaskMediaResponse");
    RecoverTaskRequest::export().expect("export RecoverTaskRequest");
    TaskActionRequest::export().expect("export TaskActionRequest");
    TestLifecycleHookRequest::export().expect("export TestLifecycleHookRequest");
    CreateCommentRequest::export().expect("export CreateCommentRequest");
    StateKind::export().expect("export StateKind");
    CleanupPolicy::export().expect("export CleanupPolicy");
    FailurePolicy::export().expect("export FailurePolicy");
    HookAudience::export().expect("export HookAudience");
    GateConfig::export().expect("export GateConfig");
    HookSpec::export().expect("export HookSpec");
    StateHooks::export().expect("export StateHooks");
    CanonicalPhase::export().expect("export CanonicalPhase");
    StateDefinition::export().expect("export StateDefinition");
    WorkflowTrigger::export().expect("export WorkflowTrigger");
    WorkflowExecutionStrategy::export().expect("export WorkflowExecutionStrategy");
    WorkflowPromptConfig::export().expect("export WorkflowPromptConfig");
    WorkflowDispatch::export().expect("export WorkflowDispatch");
    WorkflowTriggerDefinition::export().expect("export WorkflowTriggerDefinition");
    RoleDefinition::export().expect("export RoleDefinition");
    WorkflowConfigValueType::export().expect("export WorkflowConfigValueType");
    WorkflowConfigBinding::export().expect("export WorkflowConfigBinding");
    WorkflowConfigField::export().expect("export WorkflowConfigField");
    PromptBuilderRegistryEntry::export().expect("export PromptBuilderRegistryEntry");
    WorkflowDefinition::export().expect("export WorkflowDefinition");
    WorkflowTemplateSummary::export().expect("export WorkflowTemplateSummary");
    WorkflowTemplateResponse::export().expect("export WorkflowTemplateResponse");
    SaveWorkflowTemplateRequest::export().expect("export SaveWorkflowTemplateRequest");
    UpdateProjectWorkflowRequest::export().expect("export UpdateProjectWorkflowRequest");
    TaskRoleAssignmentResponse::export().expect("export TaskRoleAssignmentResponse");
    AssignRoleRequest::export().expect("export AssignRoleRequest");
    assignee::AssigneeKind::export().expect("export AssigneeKind");
    DefaultRoleAssignment::export().expect("export DefaultRoleAssignment");
    InitialRoleAssignment::export().expect("export InitialRoleAssignment");
    TransitionLogEntry::export().expect("export TransitionLogEntry");
    HookResultEntry::export().expect("export HookResultEntry");
    ReorderSubtasksRequest::export().expect("export ReorderSubtasksRequest");
    OperatorSeverity::export().expect("export OperatorSeverity");
    OperatorStatusResponse::export().expect("export OperatorStatusResponse");
    ActiveExecutionSummary::export().expect("export ActiveExecutionSummary");
    BlockedTaskSummary::export().expect("export BlockedTaskSummary");
    DaemonIssueSummary::export().expect("export DaemonIssueSummary");
    DaemonPressureSummary::export().expect("export DaemonPressureSummary");
    AgentPressureSummary::export().expect("export AgentPressureSummary");
    WorkspaceCleanupSummary::export().expect("export WorkspaceCleanupSummary");
    RetryPressureSummary::export().expect("export RetryPressureSummary");
    TokenTotalsSummary::export().expect("export TokenTotalsSummary");
    OperationsRefreshResponse::export().expect("export OperationsRefreshResponse");
    UsageSummary::export().expect("export UsageSummary");
    RecentErrorSummary::export().expect("export RecentErrorSummary");
    PlanArtifactDetail::export().expect("export PlanArtifactDetail");
    PlanChecklistItem::export().expect("export PlanChecklistItem");
    EffectiveExecutionPolicy::export().expect("export EffectiveExecutionPolicy");
    PlanProgressSummary::export().expect("export PlanProgressSummary");
    SettingsResponse::export().expect("export SettingsResponse");
    ForgeSettingResponse::export().expect("export ForgeSettingResponse");
    UpdateSettingsRequest::export().expect("export UpdateSettingsRequest");
    UpdateForgePathsRequest::export().expect("export UpdateForgePathsRequest");
    UpdateServerSettingsRequest::export().expect("export UpdateServerSettingsRequest");
    UpdateWorkspaceSettingsRequest::export().expect("export UpdateWorkspaceSettingsRequest");
    UpdateAgentSettingsRequest::export().expect("export UpdateAgentSettingsRequest");
    RegisterRequest::export().expect("export RegisterRequest");
    LoginRequest::export().expect("export LoginRequest");
    RefreshRequest::export().expect("export RefreshRequest");
    LogoutRequest::export().expect("export LogoutRequest");
    AuthResponse::export().expect("export AuthResponse");
    UserResponse::export().expect("export UserResponse");
    UpdateProfileRequest::export().expect("export UpdateProfileRequest");
    OAuthRegisterRequest::export().expect("export OAuthRegisterRequest");
    OAuthRegisterResponse::export().expect("export OAuthRegisterResponse");
    OAuthApproveRequest::export().expect("export OAuthApproveRequest");
    OAuthDecision::export().expect("export OAuthDecision");
    OAuthApproveResponse::export().expect("export OAuthApproveResponse");
    OAuthAuthorizeContext::export().expect("export OAuthAuthorizeContext");
    OAuthErrorResponse::export().expect("export OAuthErrorResponse");
    AcceptanceCheckResultStatus::export().expect("export AcceptanceCheckResultStatus");
    AcceptanceCheckSourceKind::export().expect("export AcceptanceCheckSourceKind");
    AcceptanceCheckSummary::export().expect("export AcceptanceCheckSummary");
    AcceptanceEvidenceRequirement::export().expect("export AcceptanceEvidenceRequirement");
    ActivateExecutionBaselineRequest::export().expect("export ActivateExecutionBaselineRequest");
    AdaptiveEnvelope::export().expect("export AdaptiveEnvelope");
    ApproveExecutionBaselineRequest::export().expect("export ApproveExecutionBaselineRequest");
    ApproveProjectCharterRequest::export().expect("export ApproveProjectCharterRequest");
    ApproveProjectDocumentRequest::export().expect("export ApproveProjectDocumentRequest");
    ApproveDecisionCandidateRequest::export().expect("export ApproveDecisionCandidateRequest");
    ArchitectureDocumentContent::export().expect("export ArchitectureDocumentContent");
    ArtifactRef::export().expect("export ArtifactRef");
    AttachEvidenceRequest::export().expect("export AttachEvidenceRequest");
    EvidenceAttachmentListResponse::export().expect("export EvidenceAttachmentListResponse");
    AuthorizationProvenance::export().expect("export AuthorizationProvenance");
    CharterAmendment::export().expect("export CharterAmendment");
    CharterAmendmentState::export().expect("export CharterAmendmentState");
    CharterApprovalState::export().expect("export CharterApprovalState");
    CharterApprovalType::export().expect("export CharterApprovalType");
    CharterConfidence::export().expect("export CharterConfidence");
    CharterConstraintsAndRisks::export().expect("export CharterConstraintsAndRisks");
    CharterCoreExperience::export().expect("export CharterCoreExperience");
    CharterHandoffNote::export().expect("export CharterHandoffNote");
    CharterIdentity::export().expect("export CharterIdentity");
    CharterKnowledgeItem::export().expect("export CharterKnowledgeItem");
    CharterKnowledgeKind::export().expect("export CharterKnowledgeKind");
    CharterKnowledgeLedger::export().expect("export CharterKnowledgeLedger");
    CharterProblemAndPeople::export().expect("export CharterProblemAndPeople");
    CharterReadinessGap::export().expect("export CharterReadinessGap");
    CharterReadinessGapKind::export().expect("export CharterReadinessGapKind");
    CharterReadinessStatus::export().expect("export CharterReadinessStatus");
    CharterRevisionLifecycle::export().expect("export CharterRevisionLifecycle");
    CharterRisk::export().expect("export CharterRisk");
    CharterScope::export().expect("export CharterScope");
    CharterSuccessBoundary::export().expect("export CharterSuccessBoundary");
    CharterSupersession::export().expect("export CharterSupersession");
    CreateProjectFromCharterApprovalRequest::export()
        .expect("export CreateProjectFromCharterApprovalRequest");
    CreateExecutionBaselineRequest::export().expect("export CreateExecutionBaselineRequest");
    CreateProjectFromCharterApprovalResponse::export()
        .expect("export CreateProjectFromCharterApprovalResponse");
    DecisionCandidate::export().expect("export DecisionCandidate");
    DecisionCandidateContext::export().expect("export DecisionCandidateContext");
    DecisionCandidateListResponse::export().expect("export DecisionCandidateListResponse");
    DecisionClass::export().expect("export DecisionClass");
    DecisionEditorState::export().expect("export DecisionEditorState");
    DecisionRecord::export().expect("export DecisionRecord");
    DecisionRecordListResponse::export().expect("export DecisionRecordListResponse");
    DecisionRecordState::export().expect("export DecisionRecordState");
    DeliveryBriefContent::export().expect("export DeliveryBriefContent");
    DesignDocumentContent::export().expect("export DesignDocumentContent");
    DocumentAcceptanceItem::export().expect("export DocumentAcceptanceItem");
    DocumentFreshness::export().expect("export DocumentFreshness");
    DocumentPlanItem::export().expect("export DocumentPlanItem");
    DocumentRevisionLifecycle::export().expect("export DocumentRevisionLifecycle");
    CreateMilestoneRequest::export().expect("export CreateMilestoneRequest");
    EvaluateMilestoneReadinessRequest::export().expect("export EvaluateMilestoneReadinessRequest");
    EvidenceAttachment::export().expect("export EvidenceAttachment");
    EvidenceAvailability::export().expect("export EvidenceAvailability");
    ReleaseEvidenceAvailability::export().expect("export ReleaseEvidenceAvailability");
    EvidenceKind::export().expect("export EvidenceKind");
    EvidencePin::export().expect("export EvidencePin");
    ExecutionBaseline::export().expect("export ExecutionBaseline");
    ExecutionBaselineApproval::export().expect("export ExecutionBaselineApproval");
    ExecutionBaselineContent::export().expect("export ExecutionBaselineContent");
    ExecutionBaselineReleasePolicy::export().expect("export ExecutionBaselineReleasePolicy");
    ExecutionBaselineLifecycle::export().expect("export ExecutionBaselineLifecycle");
    ExecutionBaselineRevision::export().expect("export ExecutionBaselineRevision");
    ExecutionBaselineResponse::export().expect("export ExecutionBaselineResponse");
    ExecutionPlanContent::export().expect("export ExecutionPlanContent");
    MediaAsset::export().expect("export MediaAsset");
    ProjectMediaListResponse::export().expect("export ProjectMediaListResponse");
    ProjectMediaUploadRequest::export().expect("export ProjectMediaUploadRequest");
    ProjectMediaTombstoneRequest::export().expect("export ProjectMediaTombstoneRequest");
    MilestoneAcceptanceCheck::export().expect("export MilestoneAcceptanceCheck");
    MilestoneDefinitionContent::export().expect("export MilestoneDefinitionContent");
    MilestoneDefinitionLifecycle::export().expect("export MilestoneDefinitionLifecycle");
    MilestoneDefinitionRevision::export().expect("export MilestoneDefinitionRevision");
    MilestoneDefinitionRevisionListResponse::export()
        .expect("export MilestoneDefinitionRevisionListResponse");
    ReadinessSnapshotListResponse::export().expect("export ReadinessSnapshotListResponse");
    MilestoneLifecycle::export().expect("export MilestoneLifecycle");
    MilestoneProjectionReason::export().expect("export MilestoneProjectionReason");
    MilestoneProjectionReasonKind::export().expect("export MilestoneProjectionReasonKind");
    MutationEnvelope::export().expect("export MutationEnvelope");
    OverviewProjectionState::export().expect("export OverviewProjectionState");
    PrimaryMilestonePointer::export().expect("export PrimaryMilestonePointer");
    PrincipalKind::export().expect("export PrincipalKind");
    PrincipalRef::export().expect("export PrincipalRef");
    ProductSpecContent::export().expect("export ProductSpecContent");
    ProjectCharter::export().expect("export ProjectCharter");
    ProjectCharterApproval::export().expect("export ProjectCharterApproval");
    ProductAgentSelection::export().expect("export ProductAgentSelection");
    ProductGenesisCharterResponse::export().expect("export ProductGenesisCharterResponse");
    ProjectCharterContent::export().expect("export ProjectCharterContent");
    ProjectCharterReadiness::export().expect("export ProjectCharterReadiness");
    ProjectCharterRevision::export().expect("export ProjectCharterRevision");
    ProjectCharterState::export().expect("export ProjectCharterState");
    ProjectDocument::export().expect("export ProjectDocument");
    ProjectDocumentApprovalPolicy::export().expect("export ProjectDocumentApprovalPolicy");
    ProjectDocumentListResponse::export().expect("export ProjectDocumentListResponse");
    ProjectDocumentApproval::export().expect("export ProjectDocumentApproval");
    ProjectDocumentContent::export().expect("export ProjectDocumentContent");
    ProjectDocumentKind::export().expect("export ProjectDocumentKind");
    ProjectDocumentRevision::export().expect("export ProjectDocumentRevision");
    ProjectDocumentRevisionDiffResponse::export()
        .expect("export ProjectDocumentRevisionDiffResponse");
    ProjectDocumentRevisionListResponse::export()
        .expect("export ProjectDocumentRevisionListResponse");
    ProjectDocumentState::export().expect("export ProjectDocumentState");
    ProjectMilestone::export().expect("export ProjectMilestone");
    ProjectMilestoneListResponse::export().expect("export ProjectMilestoneListResponse");
    ProjectMilestoneOverview::export().expect("export ProjectMilestoneOverview");
    ProjectMode::export().expect("export ProjectMode");
    ProjectOverview::export().expect("export ProjectOverview");
    ProjectRelease::export().expect("export ProjectRelease");
    ProjectReleaseListResponse::export().expect("export ProjectReleaseListResponse");
    ProvenanceRef::export().expect("export ProvenanceRef");
    ProvenanceSourceKind::export().expect("export ProvenanceSourceKind");
    ReadinessInput::export().expect("export ReadinessInput");
    ReadinessReason::export().expect("export ReadinessReason");
    ReadinessResult::export().expect("export ReadinessResult");
    ReadinessSnapshot::export().expect("export ReadinessSnapshot");
    ReleaseDecisionReference::export().expect("export ReleaseDecisionReference");
    ReleaseMilestoneRequest::export().expect("export ReleaseMilestoneRequest");
    SaveMilestoneRevisionRequest::export().expect("export SaveMilestoneRevisionRequest");
    ReleaseSnapshot::export().expect("export ReleaseSnapshot");
    ReleaseTaskReference::export().expect("export ReleaseTaskReference");
    ReleaseValidationReference::export().expect("export ReleaseValidationReference");
    ResearchDocumentContent::export().expect("export ResearchDocumentContent");
    ResearchSource::export().expect("export ResearchSource");
    RevisionProvenance::export().expect("export RevisionProvenance");
    SaveProjectCharterRevisionRequest::export().expect("export SaveProjectCharterRevisionRequest");
    SaveExecutionBaselineRevisionRequest::export()
        .expect("export SaveExecutionBaselineRevisionRequest");
    SaveProjectDocumentRevisionRequest::export()
        .expect("export SaveProjectDocumentRevisionRequest");
    CreateProjectDocumentRequest::export().expect("export CreateProjectDocumentRequest");
    CreateDecisionCandidateRequest::export().expect("export CreateDecisionCandidateRequest");
    RejectDecisionCandidateRequest::export().expect("export RejectDecisionCandidateRequest");
    SetPrimaryMilestoneRequest::export().expect("export SetPrimaryMilestoneRequest");
    TransitionMilestoneRevisionRequest::export()
        .expect("export TransitionMilestoneRevisionRequest");
    TransitionMilestoneRequest::export().expect("export TransitionMilestoneRequest");
    RecordMilestoneCheckRequest::export().expect("export RecordMilestoneCheckRequest");
    WaiveMilestoneCheckRequest::export().expect("export WaiveMilestoneCheckRequest");
    TaskProgressCounts::export().expect("export TaskProgressCounts");
    ValidationResult::export().expect("export ValidationResult");
    VersionedDigest::export().expect("export VersionedDigest");
}
