name: OpenSSF Scorecard

on:
  push:
    branches: [main]
  schedule:
    - cron: "41 10 * * 1"

jobs:
  scorecard:
    name: Scorecard
    if: ${{ github.event.repository.private == false }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: read
      id-token: write
      issues: read
      pull-requests: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
