// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AcceptanceCheckSourceKind = "task_validation" | "document_approval" | "manual" | "policy_waiver" | "media_evidence" | "git_ref";
