// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AcceptanceCheckResultStatus = "pass" | "fail" | "pending" | "blocked" | "stale" | "unavailable" | "waived";
