// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectiveExecutionPolicy } from "./EffectiveExecutionPolicy";
import type { PlanProgressSummary } from "./PlanProgressSummary";
import type { TokenTotalsSummary } from "./TokenTotalsSummary";

export type ActiveExecutionSummary = { execution_id: string, task_id: string, task_title: string | null, role: string, agent_id: string | null, agent_name: string | null, daemon_id: string | null, workspace_id: string | null, workspace_path: string | null, session_id: string | null, started_at: string, runtime_seconds: number, elapsed_seconds: number, latest_event: string | null, last_event: string | null, last_event_time: string | null, turn_count: number, token_totals: TokenTotalsSummary | null, rate_limit_snapshot: Record<string, unknown> | null, effective_policy: EffectiveExecutionPolicy | null, plan_progress: PlanProgressSummary | null, };
