// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MutationEnvelope } from "./MutationEnvelope";

export type ActivateExecutionBaselineRequest = { mutation: MutationEnvelope, baseline_id: string, revision_id: string, approval_id: string, content_digest: string, render_digest: string, };
