// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentChatKind } from "./AgentChatKind";
import type { AgentChatStatus } from "./AgentChatStatus";

export type AgentChatResponse = { id: string, kind: AgentChatKind, account_id: string, project_id: string | null, title: string, status: AgentChatStatus, message_count: bigint, pending_turn_count: bigint, last_message_at: string | null, version: bigint, created_at: string, updated_at: string, };
