// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Action output intentionally includes the server policy result and payload
 * hash, but not the persisted payload body.  This keeps public audit reads
 * useful without turning a generic action API into a secret-bearing log.
 */
export type AgentActionResponse = { id: string, actor_identity_id: string, scope_type: string, scope_id: string, operation: string, payload_hash: string, dedupe_key: string, correlation_id: string, causation_id: string | null, causation_depth: bigint, requested_permission: string, policy_result: string, policy_reason: string | null, status: string, target_type: string | null, target_id: string | null, outcome: Record<string, unknown> | null, materialized: boolean, version: bigint, created_at: string, updated_at: string, };
