// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentSessionSummary = { session_id: string, scope_type: string, scope_id: string, backend_kind: string, status: string, connection_status: string, last_activity_at: string | null, updated_at: string, };
