// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentBindingState } from "./AgentBindingState";
import type { AgentChatKind } from "./AgentChatKind";
import type { AgentChatStatus } from "./AgentChatStatus";

/**
 * A bounded navigation item.  It contains stable labels and state only; it
 * never carries chat bodies or private Project context.
 */
export type AgentChatSwitcherItem = { chat_id: string, kind: AgentChatKind, project_id: string | null, project_name: string | null, identity_id: string | null, identity_name: string | null, binding_state: AgentBindingState, chat_status: AgentChatStatus, unread_count: bigint, pending_turn_count: bigint, last_message_at: string | null, };
