// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The durable binding state is intentionally separate from identity status.
 * A connected identity is not implicitly a Main or Project Agent.
 */
export type AgentBindingState = "active" | "setup_required" | "paused" | "replaced" | "revoked";
