// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentBindingSummary = { binding_id: string, binding_type: string, project_id: string | null, chat_id: string, state: string, subscription_count: bigint, wake_budget: bigint, };
