// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentPressureSummary = { agent_id: string, agent_name: string, daemon_id: string | null, active_sessions: number, max_sessions: number, at_capacity: boolean, };
