// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentBindingSummary } from "./AgentBindingSummary";
import type { AgentContinuityHealth } from "./AgentContinuityHealth";
import type { AgentScopeSummary } from "./AgentScopeSummary";
import type { AgentSessionSummary } from "./AgentSessionSummary";
import type { AgentUsageSummary } from "./AgentUsageSummary";
import type { MissionControlWorkItem } from "./MissionControlWorkItem";

export type AgentDetailResponse = { identity_id: string, name: string, description: string | null, backend_kind: string | null, provider: string | null, model: string | null, identity_status: string, paused: boolean, bindings: Array<AgentBindingSummary>, scopes: Array<AgentScopeSummary>, sessions: Array<AgentSessionSummary>, current_focus: MissionControlWorkItem | null, open_commitment_count: bigint, open_inbox_count: bigint, memory_namespace_count: bigint, usage: AgentUsageSummary, continuity: AgentContinuityHealth, };
