// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentProviderId } from "./AgentProviderId";
import type { ProviderCredentialCapability } from "./ProviderCredentialCapability";

export type AgentProviderCapability = { provider: AgentProviderId, display_name: string, default_base_url: string | null, default_model: string | null, model_discovery: boolean, credential_methods: Array<ProviderCredentialCapability>, };
