// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentChatMessageResponse } from "./AgentChatMessageResponse";

export type AgentChatMessageListResponse = { items: Array<AgentChatMessageResponse>, next_cursor: string | null, has_more: boolean, };
