// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentProviderCapability } from "./AgentProviderCapability";

export type AgentProviderCapabilitiesResponse = { items: Array<AgentProviderCapability>, };
