// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentContinuityHealth = { status: string, checkpoint_present: boolean, last_activity_at: string | null, };
