// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MutationEnvelope } from "./MutationEnvelope";

export type ApproveDecisionCandidateRequest = { mutation: MutationEnvelope, };
