// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArchitectureDocumentContent = { context_and_constraints: string, system_boundary: Array<string>, components_and_data: Array<string>, interfaces: Array<string>, security_and_privacy: Array<string>, concurrency: Array<string>, failure_and_recovery: Array<string>, observability_and_operations: Array<string>, migrations: Array<string>, alternatives_and_tradeoffs: Array<string>, validation_plan: Array<string>, };
