// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArtifactRef = { artifact_id: string, revision_id: string, content_digest: string, render_version: string | null, render_digest: string | null, };
