// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AskQuestionRequest = { scope_type: string, scope_id: string, question: string, context: Record<string, unknown>, due_at: string | null, correlation_id: string, inbox_title: string | null, inbox_dedupe_key: string, };
