// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AttentionConsumerHealthResponse = { consumer_name: string, last_sequence: bigint, last_success_at: string | null, last_error_code: string | null, stale: boolean, processed_events: bigint, updated_at: string, };
