// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttentionConsumerHealthResponse } from "./AttentionConsumerHealthResponse";
import type { AttentionItem } from "./AttentionItem";

export type AttentionListResponse = { items: Array<AttentionItem>, next_cursor: string | null, has_more: boolean, total_count: bigint | null, consumer_health: AttentionConsumerHealthResponse | null, };
