// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrincipalRef } from "./PrincipalRef";

export type AuthorizationProvenance = { principal: PrincipalRef, authorization_basis: string, action: string, event_id: string, occurred_at: string, };
