// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BlockingArtifact = { kind: string, id: string | null, log_path: string | null, };
