// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optimistically cancels one visible turn.  The key is persisted through the
 * turn cancellation domain-event dedupe record, making a retry safe even
 * after the caller's original version has advanced.
 */
export type CancelAgentChatTurnRequest = { expected_version: bigint, idempotency_key: string, };
