// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CanonicalScopeRequest = { "type": "account" } | { "type": "project", project_id: string, } | { "type": "agent_chat", chat_id: string, } | { "type": "task", task_id: string, role: string, };
