// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharterReadinessGapKind } from "./CharterReadinessGapKind";

export type CharterReadinessGap = { kind: CharterReadinessGapKind, code: string, message: string, blocking: boolean, section: string | null, knowledge_item_id: string | null, };
