// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrincipalRef } from "./PrincipalRef";

export type CharterSupersession = { id: string, charter_id: string, previous_revision_id: string, superseding_revision_id: string, approval_id: string, principal: PrincipalRef, reason: string, occurred_at: string, };
