// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrincipalRef } from "./PrincipalRef";

export type CharterRisk = { id: string, description: string, impact: string | null, treatment: string | null, revisit_trigger: string | null, owner: PrincipalRef | null, };
