// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CharterKnowledgeKind = "observed_fact" | "user_decision" | "research_finding" | "assumption" | "hypothesis" | "open_decision" | "research_queue";
