// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CharterSuccessBoundary = { qualitative_outcome: string | null, success_signals: Array<string>, acceptance_statements: Array<string>, required_evidence: Array<string>, non_claims: Array<string>, };
