// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharterConfidence } from "./CharterConfidence";
import type { CharterKnowledgeKind } from "./CharterKnowledgeKind";
import type { PrincipalRef } from "./PrincipalRef";
import type { ProvenanceRef } from "./ProvenanceRef";

export type CharterKnowledgeItem = { id: string, statement: string, kind: CharterKnowledgeKind, normative: boolean, transfer_approved: boolean, provenance: Array<ProvenanceRef>, confidence: CharterConfidence | null, observed_at: string | null, freshness_expires_at: string | null, impact: string | null, owner: PrincipalRef | null, default_value: string | null, revisit_trigger: string | null, falsification_evidence: string | null, blocking: boolean, };
