// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharterKnowledgeItem } from "./CharterKnowledgeItem";

export type CharterKnowledgeLedger = { items: Array<CharterKnowledgeItem>, };
