// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderEntryAgentRef } from "./ProviderEntryAgentRef";

/**
 * A CLI-managed runtime discovered on a connected daemon. Forge reads only
 * availability signals; it never imports the CLI's credential files.
 */
export type CliRuntimeEntryResponse = { kind: string, daemon_id: string, daemon_hostname: string | null, daemon_status: string, availability: string, version: string | null, login_hint: string | null, used_by: Array<ProviderEntryAgentRef>, };
