// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommitmentEvidenceResponse = { id: string, commitment_id: string, evidence_type: string, evidence_id: string, scope_type: string, scope_id: string, description: string | null, metadata: Record<string, unknown>, authorized_by_type: string, authorized_by_id: string, dedupe_key: string, created_at: string, };
