// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Durable commitment representation.  The owner is an identity, while the
 * actor performing a lifecycle operation is authenticated by the API and is
 * intentionally absent from mutation request bodies.
 */
export type CommitmentResponse = { id: string, owner_identity_id: string, scope_type: string, scope_id: string, title: string, description: string | null, status: string, due_at: string | null, correlation_id: string, originating_action_id: string | null, originating_task_id: string | null, evidence_required: boolean, cancellation_reason: string | null, blocked_reason: string | null, completed_at: string | null, cancelled_at: string | null, version: bigint, created_at: string, updated_at: string, };
