// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentConnectionHealthResponse } from "./AgentConnectionHealthResponse";
import type { AgentProfileResponse } from "./AgentProfileResponse";
import type { AgentResponse } from "./AgentResponse";
import type { CredentialHandleResponse } from "./CredentialHandleResponse";

export type ConnectedEmbeddedProfileResponse = { agent: AgentResponse, profile: AgentProfileResponse, credential_handle: CredentialHandleResponse, health: AgentConnectionHealthResponse, };
