// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextManifestResponse } from "./ContextManifestResponse";

export type ContextManifestListResponse = { items: Array<ContextManifestResponse>, has_more: boolean, };
