// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextManifestSourceResponse = { ordinal: bigint, source_id: string, source_type: string, source_revision: string, selection_reason: string, disposition: string, 
/**
 * True when this immutable source revision no longer matches the
 * Project's current canonical pointer. The historical selection decision
 * and manifest fingerprint remain unchanged.
 */
is_stale: boolean, 
/**
 * The current canonical revision when this source type is pointer-backed.
 * `None` means either the source is not pointer-backed or its canonical
 * artifact is no longer present in the current Project projection.
 */
current_revision: string | null, retention_priority: bigint, fragment_fingerprint: string, };
