// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextManifestSourceResponse } from "./ContextManifestSourceResponse";

/**
 * Immutable context-manifest metadata and source decisions.  Source bodies
 * are never exposed by this inspector.
 */
export type ContextManifestResponse = { id: string, identity_id: string, agent_session_id: string | null, context_scope_id: string, scope_type: string, scope_id: string, policy_revision: string, domain_revision: string, lcm_binding_revision: string | null, runtime_manifest_id: string | null, runtime_manifest_fingerprint: string | null, combined_fingerprint: string, request_fingerprint: string, created_at: string, sources: Array<ContextManifestSourceResponse>, };
