// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateProjectFromCharterApprovalResponse = { project_id: string, project_agent_binding_id: string, project_chat_id: string, charter_id: string, charter_revision_id: string, handoff_id: string, target_message_id: string, target_turn_id: string, };
