// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateAgentHandoffRequest = { source_message_id: string | null, source_turn_job_id: string | null, content: string, dedupe_key: string, };
