// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MilestoneDefinitionContent } from "./MilestoneDefinitionContent";
import type { MilestoneDefinitionLifecycle } from "./MilestoneDefinitionLifecycle";
import type { MutationEnvelope } from "./MutationEnvelope";
import type { RevisionProvenance } from "./RevisionProvenance";

/**
 * Create the first immutable definition revision for a Project-local
 * milestone.  The server derives the revision number and canonical digests;
 * callers provide the exact authored content and provenance.
 */
export type CreateMilestoneRequest = { mutation: MutationEnvelope, display_label: string | null, lifecycle: MilestoneDefinitionLifecycle, content: MilestoneDefinitionContent, rendered_view: string, render_version: string, change_summary: string, provenance: RevisionProvenance, };
