// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalAttachTokenResponse } from "./TerminalAttachTokenResponse";
import type { TerminalSessionResponse } from "./TerminalSessionResponse";

export type CreateTerminalSessionResponse = { session: TerminalSessionResponse, attach: TerminalAttachTokenResponse, };
