// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MutationEnvelope } from "./MutationEnvelope";
import type { ProjectDocumentApprovalPolicy } from "./ProjectDocumentApprovalPolicy";
import type { ProjectDocumentKind } from "./ProjectDocumentKind";

export type CreateProjectDocumentRequest = { mutation: MutationEnvelope, kind: ProjectDocumentKind, title: string, approval_policy: ProjectDocumentApprovalPolicy, };
