// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentProviderId } from "./AgentProviderId";

export type CreateProviderEntryRequest = { provider: AgentProviderId, label: string, credential: string, 
/**
 * Required for `openai_compatible`; defaults to the provider's
 * documented endpoint otherwise.
 */
base_url: string | null, };
