// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateCommitmentRequest = { scope_type: string, scope_id: string, title: string, description: string | null, status: string | null, due_at: string | null, correlation_id: string, originating_action_id: string | null, originating_task_id: string | null, evidence_required: boolean | null, };
