// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperatorSeverity } from "./OperatorSeverity";

export type DaemonIssueSummary = { daemon_id: string, hostname: string | null, issue: string, severity: OperatorSeverity, detected_at: string | null, };
