// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DaemonErrorPayload } from "./DaemonErrorPayload";

export type DaemonFrame = { "type": "request", id: string, method: string, params: unknown, } | { "type": "response", id: string, result: unknown, } | { "type": "error", id: string | null, error: DaemonErrorPayload, } | { "type": "notification", method: string, params: unknown, } | { "type": "heartbeat", seq: bigint, };
