// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionRecord } from "./DecisionRecord";

export type DecisionRecordListResponse = { items: Array<DecisionRecord>, next_cursor: string | null, has_more: boolean, };
