// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionClass } from "./DecisionClass";
import type { DecisionEditorState } from "./DecisionEditorState";
import type { PrincipalRef } from "./PrincipalRef";

/**
 * Editor workflow state is intentionally separate from `DecisionRecordState`;
 * it cannot be used as effective Project truth.
 */
export type DecisionCandidate = { id: string, project_id: string, editor_state: DecisionEditorState, question: string, options: Array<string>, selected_outcome: string | null, rationale: string | null, proposed_by: PrincipalRef, decision_class: DecisionClass, rejection_reason: string | null, effective_decision_id: string | null, created_at: string, updated_at: string, };
