// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DefaultRoleAssignment = { role_name: string, assignee_type: string, assignee_id: string | null, };
