// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharterRisk } from "./CharterRisk";
import type { DocumentAcceptanceItem } from "./DocumentAcceptanceItem";
import type { DocumentPlanItem } from "./DocumentPlanItem";

export type DeliveryBriefContent = { intended_deliverables: Array<string>, boundaries: Array<string>, plan_items: Array<DocumentPlanItem>, acceptance_matrix: Array<DocumentAcceptanceItem>, risks: Array<CharterRisk>, rollback_and_recovery: Array<string>, adaptive_envelope: Array<string>, governing_charter_revision_id: string | null, };
