// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DocumentPlanItem = { id: string, outcome: string, dependencies: Array<string>, task_ids: Array<string>, };
