// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EffectiveExecutionPolicy = { executor_kind: string, permission_policy: string, isolation_posture: string, is_high_risk: boolean, effective_cwd: string | null, workspace_root: string | null, environment_posture: string, scoped_tools: Array<string>, mcp_servers: Array<string>, };
