// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MutationEnvelope } from "./MutationEnvelope";

export type EvaluateMilestoneReadinessRequest = { mutation: MutationEnvelope, milestone_id: string, baseline_id: string, baseline_revision_id: string, release_policy_revision: string, };
