// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionBaseline } from "./ExecutionBaseline";
import type { ExecutionBaselineApproval } from "./ExecutionBaselineApproval";
import type { ExecutionBaselineRevision } from "./ExecutionBaselineRevision";

export type ExecutionBaselineResponse = { baseline: ExecutionBaseline, current_revision: ExecutionBaselineRevision | null, 
/**
 * A proposed/approved successor that is not authoritative until
 * activation.  This is populated when an active baseline is being
 * superseded so callers can approve and activate the exact revision
 * without mistaking it for the currently runnable revision.
 */
proposed_revision: ExecutionBaselineRevision | null, approval: ExecutionBaselineApproval | null, };
