// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecutionStartParams = { task_id: string, execution_id: string, workspace_path: string, executor_type: string, executor_config: unknown, prompt: unknown, max_turns: number | null, };
