// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The frozen release policy carried by an execution baseline.
 *
 * A baseline must bind the concrete checks, evidence, review, dependency,
 * side-effect, and correction rules that were in force when the user
 * approved it.  The policy digest is derived from this closed value by the
 * server; the surrounding revision/digest fields are indexed projections
 * used by admission queries and must match it exactly.
 */
export type ExecutionBaselineReleasePolicy = { schema_version: string, revision: string, required_check_definition_revisions: Array<string>, reviewer_independence_rules: Array<string>, manual_attestation_rules: Array<string>, waiver_rules: Array<string>, evidence_kinds: Array<string>, evidence_contexts: Array<string>, evidence_freshness_rules: Array<string>, dependency_rules: Array<string>, stale_input_rules: Array<string>, forbidden_side_effects: Array<string>, known_issue_rules: Array<string>, correction_rules: Array<string>, purge_rules: Array<string>, };
