// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactRef } from "./ArtifactRef";
import type { CharterRisk } from "./CharterRisk";
import type { DocumentAcceptanceItem } from "./DocumentAcceptanceItem";

export type ExecutionPlanContent = { ordered_milestone_outcomes: Array<string>, dependencies: Array<string>, risks: Array<CharterRisk>, linked_artifact_refs: Array<ArtifactRef>, task_queries_or_ids: Array<string>, acceptance_evidence_contract: Array<DocumentAcceptanceItem>, release_notes: Array<string>, known_issues: Array<string>, };
