// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecutionLogNotification = { execution_id: string, seq: bigint, stream: string, line: string, ts: string, kind: string | null, log_stream: string | null, payload: unknown, truncated: boolean | null, };
