// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionBaselineLifecycle } from "./ExecutionBaselineLifecycle";

export type ExecutionBaseline = { id: string, project_id: string, current_revision_id: string | null, lifecycle: ExecutionBaselineLifecycle, version: bigint, created_at: string, updated_at: string, };
