// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FailingStepSummary = { index: number, command: string | null, exit_code: number | null, output_tail: string | null, stderr_tail: string | null, };
