// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Closed vocabulary for task interruption kinds. This is the only
 * classification signal for blocked/failed metadata and blocking
 * annotations; human-readable reason text carries no classification weight.
 *
 * `Unknown` is a deserialize-only fallback for legacy database rows and MUST
 * NOT be constructed by producers; it classifies as info-only (no recovery
 * actions offered).
 */
export type FailureKind = "merge_conflict" | "target_repo_dirty" | "dirty_worktree" | "ci_failed" | "review_gate_failed" | "review_budget_exhausted" | "retry_exhausted" | "merge_fix_budget_exhausted" | "workflow_guard_rejected" | "internal_command_failed" | "pr_closed_without_merge" | "executor_failed" | "workspace_failed" | "workspace_reset_required" | "workspace_error" | "before_work_hook_timeout" | "before_work_hook_failed" | "max_turns_exceeded" | "manual_stop" | "recovery_required" | "executor_unavailable" | "unknown";
