// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FsBranchesResult = { branches: Array<string>, default_branch: string | null, origin_url: string | null, };
