// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InboxItemResponse = { id: string, recipient_identity_id: string, scope_type: string, scope_id: string, kind: string, status: string, title: string, body: string, payload: Record<string, unknown>, source_type: string | null, source_id: string | null, correlation_id: string, causation_id: string | null, dedupe_key: string, read_at: string | null, acknowledged_at: string | null, version: bigint, created_at: string, updated_at: string, };
