// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LifecycleEvent = "before_work" | "on_work_start" | "on_work_stop" | "on_task_done" | "on_task_cancel";
