// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LifecycleHookTestResponse = { status: string, stdout: string, stderr: string, exit_code: number | null, duration_ms: bigint, timeout: boolean, working_dir: string, environment_preview: { [key in string]?: string }, hook_log_path: string | null, };
