// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LifecycleHookDef = { "type": "script", command: string, timeout_seconds: bigint, blocking: boolean, } | { "type": "plugin", name: string, enabled: boolean, config: Record<string, unknown> | null, };
