// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentBindingState } from "./AgentBindingState";

/**
 * The account's one active Main Agent binding.  The chat is owned by the
 * account and therefore remains stable when this binding is replaced.
 */
export type MainAgentBindingResponse = { id: string, account_id: string, identity_id: string, profile_id: string, chat_id: string, state: AgentBindingState, autonomy_policy: Record<string, unknown>, tool_policy_revision: string | null, version: bigint, created_at: string, updated_at: string, };
