// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryLifecycleResponse = { id: string, memory_item_id: string, assertion_type: string, related_memory_id: string | null, reason: string | null, evidence_present: boolean, asserted_by_type: string, asserted_by_id: string | null, source_event_id: string | null, created_at: string, };
