// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explicitly widens one immutable memory assertion into another canonical
 * scope.  The API never returns the submitted evidence; it is retained only
 * for audit and is represented by lifecycle metadata in responses.
 */
export type MemoryPublicationRequest = { source_scope_type: string, source_scope_id: string, target_scope_type: string, target_scope_id: string, target_project_id: string | null, target_task_id: string | null, target_chat_id: string | null, target_visibility: string, target_authority: string, actor_identity_id: string, reason: string, evidence_json: string, };
