// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemorySearchResultDto = { id: string, layer: number, content: string, score: number, source_type: string, source_id: string, project_id: string, task_id: string | null, created_at: string, creator: string | null, };
