// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryLifecycleResponse } from "./MemoryLifecycleResponse";

/**
 * Metadata-only memory provenance.  Deliberately omits title, summary, body,
 * evidence and any other content-bearing field.
 */
export type MemoryProvenanceResponse = { id: string, scope_type: string, scope_id: string, visibility: string, owner_identity_id: string | null, authority: string, sensitivity: string, retention_priority: bigint, source_type: string, source_ref: string | null, source_event_id: string | null, source_scope_type: string | null, source_scope_id: string | null, source_revision: string | null, source_chat_sequence: bigint | null, publication_source_id: string | null, supersedes_id: string | null, valid_from: string | null, valid_until: string | null, created_by_type: string | null, created_by_id: string | null, created_at: string, lifecycle: Array<MemoryLifecycleResponse>, };
