// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryLifecycleRequest = { scope_type: string, scope_id: string, assertion_type: string, related_memory_id: string | null, reason: string | null, evidence_json: string, actor_identity_id: string, };
