// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryBackfillTypeResponse } from "./MemoryBackfillTypeResponse";

export type MemoryBackfillResponse = { items: Array<MemoryBackfillTypeResponse>, indexed: bigint, skipped: bigint, };
