// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcceptanceEvidenceRequirement } from "./AcceptanceEvidenceRequirement";
import type { ArtifactRef } from "./ArtifactRef";
import type { CharterRisk } from "./CharterRisk";
import type { MilestoneAcceptanceCheck } from "./MilestoneAcceptanceCheck";

export type MilestoneDefinitionContent = { name: string, outcome: string, included_scope: Array<string>, excluded_scope: Array<string>, charter_revision: ArtifactRef | null, document_revisions: Array<ArtifactRef>, task_ids: Array<string>, dependencies: Array<string>, risks: Array<CharterRisk>, acceptance_checks: Array<MilestoneAcceptanceCheck>, evidence_requirements: Array<AcceptanceEvidenceRequirement>, known_issues: Array<string>, target_date: string | null, };
