// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MissionControlQuery = { project_id: string | null, cursor: string | null, status: string | null, include_snoozed: boolean | null, include_total: boolean | null, limit: bigint | null, };
