// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MissionControlWorkItem = { task_id: string, project_id: string, title: string, status: string, priority: bigint, updated_at: string, primary_action: string, };
