// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskResponse } from "./TaskResponse";

export type MoveTaskResponse = { task: TaskResponse, board_revision: bigint, operation_id: string, };
