// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MoveTaskRequest = { operation_id: string, task_version: bigint, board_revision: bigint, target_status: string, before_id: string | null, after_id: string | null, };
