// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationResponse = { id: string, project_id: string, task_id: string | null, event_type: string, title: string, body: string | null, read: boolean, created_at: string, };
