// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OAuthDecision } from "./OAuthDecision";

export type OAuthApproveRequest = { response_type: string, client_id: string, redirect_uri: string, resource: string, scope: string, state: string | null, code_challenge: string, code_challenge_method: string, decision: OAuthDecision, };
