// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OAuthRegisterResponse = { client_id: string, client_id_issued_at: bigint, client_name: string | null, redirect_uris: Array<string>, grant_types: Array<string>, response_types: Array<string>, token_endpoint_auth_method: string, scope: string, };
