// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OAuthRegisterRequest = { redirect_uris: Array<string>, client_name: string | null, grant_types: Array<string> | null, response_types: Array<string> | null, token_endpoint_auth_method: string | null, scope: string | null, };
