// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanProgressSummary = { total: number, completed: number, remaining: number, available: boolean, warnings: Array<string>, };
