// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrimaryMilestonePointer = { project_id: string, primary_milestone_id: string | null, expected_project_version: bigint, updated_at: string, };
