// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Durable lifecycle of a typed Genesis discovery interaction.
 */
export type ProductGenesisLifecycle = "discovering" | "ready_for_project" | "handed_off" | "cancelled";
