// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProductGenesisSession } from "./ProductGenesisSession";

export type ProductGenesisStartResponse = { session: ProductGenesisSession, main_chat_id: string, admitted_turn_id: string | null, };
