// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectDocumentKind } from "./ProjectDocumentKind";
import type { ProjectDocumentState } from "./ProjectDocumentState";

export type ProjectDocument = { id: string, project_id: string, kind: ProjectDocumentKind, title: string, state: ProjectDocumentState, approval_required: boolean, current_draft_revision_id: string | null, current_approved_revision_id: string | null, version: bigint, created_at: string, updated_at: string, };
