// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectDocumentRevision } from "./ProjectDocumentRevision";

export type ProjectDocumentRevisionListResponse = { items: Array<ProjectDocumentRevision>, next_cursor: string | null, has_more: boolean, };
