// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectDocumentKind = "research" | "delivery_brief" | "product_spec" | "design" | "architecture" | "execution_plan";
