// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MilestoneLifecycle } from "./MilestoneLifecycle";
import type { MilestoneProjectionReason } from "./MilestoneProjectionReason";

export type ProjectMilestone = { id: string, project_id: string, milestone_sequence: bigint, canonical_id: string, display_label: string | null, definition_revision_id: string, lifecycle: MilestoneLifecycle, projection_reasons: Array<MilestoneProjectionReason>, version: bigint, created_at: string, updated_at: string, };
