// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectDocument } from "./ProjectDocument";

export type ProjectDocumentListResponse = { items: Array<ProjectDocument>, next_cursor: string | null, has_more: boolean, };
