// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectRelease } from "./ProjectRelease";

export type ProjectReleaseListResponse = { items: Array<ProjectRelease>, next_cursor: string | null, has_more: boolean, };
