// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcceptanceCheckSummary } from "./AcceptanceCheckSummary";
import type { CharterRisk } from "./CharterRisk";
import type { DocumentFreshness } from "./DocumentFreshness";
import type { EvidenceAttachment } from "./EvidenceAttachment";
import type { OverviewProjectionState } from "./OverviewProjectionState";
import type { ProjectCharterRevision } from "./ProjectCharterRevision";
import type { ProjectCharterState } from "./ProjectCharterState";
import type { ProjectMilestoneOverview } from "./ProjectMilestoneOverview";
import type { ProjectRelease } from "./ProjectRelease";
import type { TaskProgressCounts } from "./TaskProgressCounts";

export type ProjectOverview = { project_id: string, project_name: string, vision: string, charter_state: ProjectCharterState, current_charter: ProjectCharterRevision | null, primary_milestone_id: string | null, active_milestones: Array<ProjectMilestoneOverview>, task_counts: TaskProgressCounts, check_summary: AcceptanceCheckSummary, unresolved_decision_ids: Array<string>, risks: Array<CharterRisk>, document_freshness: Array<DocumentFreshness>, evidence: Array<EvidenceAttachment>, releases: Array<ProjectRelease>, next_action: string | null, projection_state: OverviewProjectionState, source_event_watermark: string, generated_at: string, };
