// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProductMaturity } from "./ProductMaturity";
import type { ProjectCharterState } from "./ProjectCharterState";
import type { ProjectMode } from "./ProjectMode";

export type ProjectCharter = { id: string, genesis_session_id: string | null, project_id: string | null, state: ProjectCharterState, project_mode: ProjectMode, maturity: ProductMaturity, current_draft_revision_id: string | null, current_approved_revision_id: string | null, version: bigint, created_at: string, updated_at: string, };
