// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReleaseSnapshot } from "./ReleaseSnapshot";

export type ProjectRelease = { id: string, project_id: string, milestone_id: string, release_sequence: bigint, release_identity: string, snapshot: ReleaseSnapshot, version: bigint, created_at: string, };
