// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectDocumentRevisionDiffResponse = { document_id: string, base_revision_id: string | null, revision_id: string, diff: string, };
