// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentRevisionLifecycle } from "./DocumentRevisionLifecycle";
import type { ProjectDocumentContent } from "./ProjectDocumentContent";
import type { RevisionProvenance } from "./RevisionProvenance";

export type ProjectDocumentRevision = { id: string, document_id: string, project_id: string, revision_number: bigint, base_revision_id: string | null, lifecycle: DocumentRevisionLifecycle, schema_version: string, content: ProjectDocumentContent, rendered_view: string, render_version: string, content_digest: string, render_digest: string, provenance: RevisionProvenance, approved_at: string | null, superseded_by_revision_id: string | null, created_at: string, };
