// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MutationEnvelope } from "./MutationEnvelope";

/**
 * An audited user-authorized disposition of a Project media asset.  The
 * storage key and bytes remain internal; callers address the asset only by
 * its stable Project URL and opaque asset id.
 */
export type ProjectMediaTombstoneRequest = { mutation: MutationEnvelope, reason: string, };
