// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutomaticRecoverySettings } from "./AutomaticRecoverySettings";
import type { DefaultRoleAssignment } from "./DefaultRoleAssignment";
import type { LifecycleEvent } from "./LifecycleEvent";
import type { LifecycleHookDef } from "./LifecycleHookDef";
import type { RetryBudgets } from "./RetryBudgets";

export type ProjectSettings = { retry_budgets: RetryBudgets, default_role_assignments: Array<DefaultRoleAssignment>, lifecycle_hooks: { [key in LifecycleEvent]?: Array<LifecycleHookDef> }, automatic_recovery: AutomaticRecoverySettings, };
