// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharterConstraintsAndRisks } from "./CharterConstraintsAndRisks";
import type { CharterCoreExperience } from "./CharterCoreExperience";
import type { CharterHandoffNote } from "./CharterHandoffNote";
import type { CharterIdentity } from "./CharterIdentity";
import type { CharterKnowledgeLedger } from "./CharterKnowledgeLedger";
import type { CharterProblemAndPeople } from "./CharterProblemAndPeople";
import type { CharterScope } from "./CharterScope";
import type { CharterSuccessBoundary } from "./CharterSuccessBoundary";

/**
 * The canonical typed payload hashed by a Charter content digest.
 */
export type ProjectCharterContent = { identity: CharterIdentity, problem_and_people: CharterProblemAndPeople, core_experience: CharterCoreExperience, scope: CharterScope, success: CharterSuccessBoundary, constraints_and_risks: CharterConstraintsAndRisks, knowledge_ledger: CharterKnowledgeLedger, handoff_note: CharterHandoffNote | null, };
