// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PromptBuilderRegistryEntry = { id: string, label: string, compatible_role_hints: Array<string>, description: string, };
