// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProposeActionRequest = { scope_type: string, scope_id: string, operation: string, payload: Record<string, unknown>, dedupe_key: string, correlation_id: string, causation_id: string | null, causation_depth: bigint | null, target_type: string | null, target_id: string | null, };
