// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProtectedInteractionAnswerValue } from "./ProtectedInteractionAnswerValue";

export type ProtectedInteractionAnswerRequest = { expected_version: bigint, values: Array<ProtectedInteractionAnswerValue>, };
