// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CliRuntimeEntryResponse } from "./CliRuntimeEntryResponse";
import type { ProviderEntryResponse } from "./ProviderEntryResponse";

export type ProviderEntriesResponse = { items: Array<ProviderEntryResponse>, cli_runtimes: Array<CliRuntimeEntryResponse>, };
