// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderCredentialMethod } from "./ProviderCredentialMethod";
import type { ProviderRuntimeCapability } from "./ProviderRuntimeCapability";
import type { ProviderSupportLevel } from "./ProviderSupportLevel";

export type ProviderCredentialCapability = { method: ProviderCredentialMethod, action_label: string, support_level: ProviderSupportLevel, configured: boolean, setup_guidance: string | null, boundary_note: string | null, runtimes: Array<ProviderRuntimeCapability>, };
