// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One provider-reported rate-limit window (e.g. ChatGPT's rolling 5h/weekly
 * windows).
 */
export type ProviderUsageWindow = { id: string, used_percent: number, window_minutes: bigint | null, resets_at: string | null, };
