// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a live connectivity test against a provider entry's API.
 * `message` is always redacted server-side; it never carries credential
 * material or provider response bodies.
 */
export type ProviderEntryTestResponse = { 
/**
 * `ok` when the provider answered and accepted the credential; `failed`
 * otherwise (see `message` for the redacted reason).
 */
status: string, latency_ms: number, message: string | null, checked_at: string, };
