// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderUsageWindow } from "./ProviderUsageWindow";

/**
 * Live (or best-effort) account usage for a provider entry. `source` is
 * `probe` only when live data was actually fetched; `unknown` — with empty
 * `windows` and a `detail` message — whenever the provider isn't probeable
 * or the probe failed. Usage is never fabricated as 0%.
 */
export type ProviderUsageResponse = { id: string, provider: string, source: string, plan_type: string | null, windows: Array<ProviderUsageWindow>, fetched_at: string, detail: string | null, };
