// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuestionResponse = { id: string, recipient_identity_id: string, scope_type: string, scope_id: string, status: string, question: string, context: Record<string, unknown>, answer: string | null, asked_by_type: string, asked_by_id: string, answered_by_type: string | null, answered_by_id: string | null, inbox_item_id: string | null, due_at: string | null, correlation_id: string, version: bigint, answered_at: string | null, created_at: string, updated_at: string, };
