// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthorizationProvenance } from "./AuthorizationProvenance";
import type { EvidenceAvailability } from "./EvidenceAvailability";
import type { PrincipalRef } from "./PrincipalRef";
import type { ReadinessInput } from "./ReadinessInput";
import type { ReadinessReason } from "./ReadinessReason";
import type { ReadinessResult } from "./ReadinessResult";
import type { ValidationResult } from "./ValidationResult";

export type ReadinessSnapshot = { id: string, project_id: string, milestone_id: string, 
/**
 * The immutable milestone CAS version used to compute this candidate.
 * A readiness request is bound to this exact version; it is not inferred
 * from the mutable milestone returned later.
 */
expected_milestone_version: bigint, milestone_definition_revision_id: string, baseline_id: string, baseline_revision_id: string, baseline_digest: string, release_policy_revision: string, release_policy_digest: string, input_manifest: Array<ReadinessInput>, source_event_watermark: string, result: ReadinessResult, reasons: Array<ReadinessReason>, check_results: Array<ValidationResult>, waiver_ids: Array<string>, evidence_attachment_ids: Array<string>, evidence_digests: Array<string>, evidence_availability: Array<EvidenceAvailability>, commit_build_check_context: Array<string>, computing_policy_revision: string, readiness_digest: string, computed_at: string, 
/**
 * The complete authority receipt for the readiness computation.  This
 * is persisted and replay-compared; it is never reconstructed from the
 * current authenticated user.
 */
requesting_principal: PrincipalRef, authorization: AuthorizationProvenance, };
