// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperatorSeverity } from "./OperatorSeverity";

export type RecentErrorSummary = { entity_type: string, entity_id: string, error: string, occurred_at: string, severity: OperatorSeverity, };
