// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcceptanceCheckResultStatus } from "./AcceptanceCheckResultStatus";
import type { MutationEnvelope } from "./MutationEnvelope";

export type RecordMilestoneCheckRequest = { mutation: MutationEnvelope, check_id: string, definition_revision_id: string, status: AcceptanceCheckResultStatus, result: string, input_digest: string, governing_revision_ids: Array<string>, };
