// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcceptanceCheckResultStatus } from "./AcceptanceCheckResultStatus";
import type { AuthorizationProvenance } from "./AuthorizationProvenance";
import type { PrincipalRef } from "./PrincipalRef";

export type ReleaseValidationReference = { validation_id: string, result_digest: string, evaluated_at: string, principal: PrincipalRef, authorization: AuthorizationProvenance, status: AcceptanceCheckResultStatus, result: string, input_digest: string, governing_revision_ids: Array<string>, };
