// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structured failure class carried across the daemon protocol.
 */
export type RemoteExecutionFailureClass = "task_failed" | "executor_unavailable";
