// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The executor candidate that actually ran a remote execution.
 */
export type RemoteResolvedCandidate = { candidate_key: string, executor_type: string, config: Record<string, unknown>, };
