// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One candidate attempt outcome from a remote execution's fallback route.
 */
export type RemoteRouteAttempt = { candidate_key: string, outcome: string, };
