// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResearchSource } from "./ResearchSource";

export type ResearchDocumentContent = { question: string, decision_informed: string, scope: string, stopping_condition: string, sources: Array<ResearchSource>, findings: Array<string>, evidence: Array<string>, inferences: Array<string>, alternatives: Array<string>, recommendation: string | null, uncertainty: Array<string>, unresolved_questions: Array<string>, affected_artifact_ids: Array<string>, affected_decision_ids: Array<string>, };
