// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrincipalRef } from "./PrincipalRef";
import type { ProvenanceRef } from "./ProvenanceRef";

export type RevisionProvenance = { author: PrincipalRef, profile_revision: string | null, operating_skill_revision: string | null, source_refs: Array<ProvenanceRef>, change_summary: string, material_diff: string | null, };
