// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MutationEnvelope } from "./MutationEnvelope";
import type { ProductMaturity } from "./ProductMaturity";
import type { ProjectCharterContent } from "./ProjectCharterContent";
import type { ProjectMode } from "./ProjectMode";
import type { RevisionProvenance } from "./RevisionProvenance";

export type SaveProjectCharterRevisionRequest = { mutation: MutationEnvelope, charter_id: string, base_revision_id: string | null, project_mode: ProjectMode, maturity: ProductMaturity, content: ProjectCharterContent, rendered_view: string, render_version: string, provenance: RevisionProvenance, };
