// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentRevisionLifecycle } from "./DocumentRevisionLifecycle";
import type { MutationEnvelope } from "./MutationEnvelope";
import type { ProjectDocumentContent } from "./ProjectDocumentContent";
import type { RevisionProvenance } from "./RevisionProvenance";

export type SaveProjectDocumentRevisionRequest = { mutation: MutationEnvelope, base_revision_id: string | null, lifecycle: DocumentRevisionLifecycle, content: ProjectDocumentContent, change_summary: string, provenance: RevisionProvenance, };
