// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowDefinition } from "./WorkflowDefinition";

export type SaveWorkflowTemplateRequest = { display_name: string | null, description: string | null, definition: WorkflowDefinition, };
