// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MilestoneDefinitionContent } from "./MilestoneDefinitionContent";
import type { MilestoneDefinitionLifecycle } from "./MilestoneDefinitionLifecycle";
import type { MutationEnvelope } from "./MutationEnvelope";
import type { RevisionProvenance } from "./RevisionProvenance";

/**
 * Append one immutable definition revision using the exact UUID of its base
 * revision for optimistic concurrency.
 */
export type SaveMilestoneRevisionRequest = { mutation: MutationEnvelope, base_revision_id: string, lifecycle: MilestoneDefinitionLifecycle, content: MilestoneDefinitionContent, rendered_view: string, render_version: string, change_summary: string, provenance: RevisionProvenance, };
