// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingResponse } from "./SettingResponse";

export type SettingListResponse = { items: Array<SettingResponse>, };
