// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskAction } from "./TaskAction";

export type TaskActionsResponse = { available_actions: Array<TaskAction>, };
