// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskUsageSummaryResponse = { total_input_tokens: bigint, total_output_tokens: bigint, total_cache_read_tokens: bigint, total_cache_write_tokens: bigint, total_cost_usd: number | null, execution_count: bigint, };
