// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterruptionMetadata } from "./InterruptionMetadata";
import type { TaskType } from "./TaskType";

export type Task = { id: string, project_id: string, title: string, description: string | null, status: string, task_type: TaskType, priority: number, board_position: number, blocked: InterruptionMetadata | null, failed: InterruptionMetadata | null, agent_id: string | null, agent_name: string | null, external_issue_number: bigint | null, external_issue_url: string | null, version: bigint, updated_at: string, };
