// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RetryBudgets } from "./RetryBudgets";

export type TaskMetadata = { retry_budgets: RetryBudgets | null, };
