// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionExecutionResponse } from "./ActionExecutionResponse";
import type { AgentActionResponse } from "./AgentActionResponse";
import type { TaskResponse } from "./TaskResponse";

export type TaskProposalExecutionResponse = { action: AgentActionResponse, execution: ActionExecutionResponse, task: TaskResponse, };
