// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskResponse } from "./TaskResponse";

export type TasksResponse = { items: Array<TaskResponse>, next_cursor: string | null, has_more: boolean, total_count: bigint | null, board_revision: bigint, };
