// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskRoleAssignmentResponse = { id: string, task_id: string, role_name: string, assignee_type: string | null, assignee_id: string | null, created_at: string, updated_at: string, };
