// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskMovedEventPayload = { project_id: string, operation_id: string, old_status: string, new_status: string, old_board_position: number, new_board_position: number, task_version: bigint, board_revision: bigint, before_id: string | null, after_id: string | null, };
