// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalOutputNotification = { session_id: string, data: string, ts: string, };
