// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalExitedNotification = { session_id: string, exit_code: number | null, signal: string | null, reason: string | null, ts: string, };
