// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalStartParams = { session_id: string, workspace_path: string, rows: number, cols: number, shell: string | null, env: Array<[string, string]> | null, idle_timeout_secs: bigint, max_lifetime_secs: bigint, };
