// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalClientFrame = { "type": "input", data: string, } | { "type": "resize", rows: number, cols: number, } | { "type": "ping", };
