// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalServerFrame = { "type": "output", data: string, } | { "type": "exit", exit_code: number | null, signal: string | null, reason: string | null, } | { "type": "error", code: string, message: string, } | { "type": "pong", };
