// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalStartResult = { session_id: string, pid: number | null, started_at: string, };
