// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalAttachTokenResponse = { attach_token: string, expires_at: string, ws_url: string, session_id: string, };
