// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LifecycleEvent } from "./LifecycleEvent";

export type TestLifecycleHookRequest = { task_id: string, event: LifecycleEvent, hook_index: number, };
