// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TransferCommitmentRequest = { expected_version: bigint, to_identity_id: string, reason: string, dedupe_key: string, };
