// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateAgentSettingsRequest = { max_concurrent_tasks: number | null, heartbeat_interval_seconds: bigint | null, max_missed_heartbeats: number | null, };
