// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateCommitmentRequest = { expected_version: bigint, status: string | null, due_at: string | null | null, description: string | null | null, blocked_reason: string | null | null, cancellation_reason: string | null | null, reason: string | null, evidence_id: string | null, dedupe_key: string, };
