// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkMode } from "./WorkMode";

export type UpdateRepoRequest = { name?: string | null, remote_url?: string | null, local_path?: string | null, default_branch?: string | null, work_mode?: WorkMode | null, };
