// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateWorkspaceSettingsRequest = { root: string | null, cleanup_delay_seconds: bigint | null, };
