// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateAgentSettingsRequest } from "./UpdateAgentSettingsRequest";
import type { UpdateForgePathsRequest } from "./UpdateForgePathsRequest";
import type { UpdateServerSettingsRequest } from "./UpdateServerSettingsRequest";
import type { UpdateWorkspaceSettingsRequest } from "./UpdateWorkspaceSettingsRequest";

export type UpdateSettingsRequest = { forge: UpdateForgePathsRequest | null, server: UpdateServerSettingsRequest | null, workspace: UpdateWorkspaceSettingsRequest | null, agent: UpdateAgentSettingsRequest | null, project: { [key in string]?: string } | null, };
