// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageSummary = { available: boolean, total_input_tokens: bigint | null, total_output_tokens: bigint | null, total_cost_usd: number | null, active_execution_count: number, };
