// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcceptanceCheckResultStatus } from "./AcceptanceCheckResultStatus";
import type { AuthorizationProvenance } from "./AuthorizationProvenance";
import type { PrincipalRef } from "./PrincipalRef";

export type ValidationResult = { id: string, project_id: string, check_id: string, status: AcceptanceCheckResultStatus, result: string, principal: PrincipalRef, authorization: AuthorizationProvenance, input_digest: string, governing_revision_ids: Array<string>, expected_version: bigint, event_id: string, evaluated_at: string, result_digest: string, };
