// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkflowConfigBinding = { "type": "gate_config", state: string, field: string, } | { "type": "state_config", state: string, path: Array<string>, };
