// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoleDefinition } from "./RoleDefinition";
import type { StateDefinition } from "./StateDefinition";
import type { WorkflowConfigField } from "./WorkflowConfigField";

export type WorkflowDefinition = { roles: Array<RoleDefinition>, states: Array<StateDefinition>, configuration: Array<WorkflowConfigField>, cancellation_state: string | null, };
