// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecoveryAction } from "./RecoveryAction";

export type WorkflowExceptionAction = { kind: RecoveryAction, label: string, enabled: boolean, disabled_reason: string | null, requires_reason: boolean, requires_guidance: boolean, propagates: boolean, target_state: string | null, target_role: string | null, target_execution_id: string | null, };
