// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowDefinition } from "./WorkflowDefinition";

export type WorkflowTemplateResponse = { name: string, display_name: string, description: string, is_builtin: boolean, definition: WorkflowDefinition, };
