// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthSeverity } from "./HealthSeverity";
import type { WorkflowHealthKind } from "./WorkflowHealthKind";

export type WorkflowHealthSummary = { kind: WorkflowHealthKind, label: string, severity: HealthSeverity, message: string | null, state: string | null, role: string | null, execution_id: string | null, review_id: string | null, since: string | null, stale_reason: string | null, };
