// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkflowPromptConfig = { user_prefix: string | null, user_append: string | null, system_prefix: string | null, system_append: string | null, };
