// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkflowHealthKind = "idle" | "waiting_for_agent" | "running" | "awaiting_human" | "blocked" | "failed" | "stuck";
