export const qk = {
  projects: ['projects'] as const,
  projectTasks: (projectId: string) => ['projects', projectId, 'tasks'] as const,
  tasks: (projectId: string, filterKey: string) =>
    ['projects', projectId, 'tasks', filterKey] as const,
  task: (taskId: string) => ['tasks', taskId] as const,
  taskDiff: (taskId: string) => ['tasks', taskId, 'diff'] as const,
  taskDetail: (taskId: string) => ['tasks', taskId, 'detail'] as const,
  reviews: (taskId: string) => ['tasks', taskId, 'reviews'] as const,
  comments: (taskId: string) => ['tasks', taskId, 'comments'] as const,
  taskMedia: (taskId: string) => ['tasks', taskId, 'media'] as const,
  agents: ['agents'] as const,
  agentPages: (limit: number) => ['agents', 'pages', limit] as const,
  agent: (id: string) => ['agents', id] as const,
  agentTasks: (id: string, filterKey: string) => ['agents', id, 'tasks', filterKey] as const,
  project: (id: string) => ['projects', id] as const,
  projectOverview: (id: string) => ['projects', id, 'overview'] as const,
  projectRelease: (projectId: string, releaseId: string) =>
    ['projects', projectId, 'releases', releaseId] as const,
  projectPages: (limit: number) => ['projects', 'pages', limit] as const,
  projectHookRuns: (projectId: string) => ['projects', projectId, 'project-hook-runs'] as const,
  projectHookRunPages: (projectId: string, limit: number) =>
    ['projects', projectId, 'project-hook-runs', limit] as const,
  repos: (projectId: string) => ['projects', projectId, 'repos'] as const,
  mcpConfig: (agent: string, scope: string, projectId?: string) =>
    ['config', 'mcp', agent, scope, projectId ?? 'global'] as const,
  fsEntries: (path: string, daemonId: string) => ['fs', 'entries', daemonId, path] as const,
  branches: (path: string, daemonId: string) => ['fs', 'branches', daemonId, path] as const,
  executions: (taskId: string) => ['tasks', taskId, 'executions'] as const,
  execution: (id: string) => ['executions', id] as const,
  executionLogs: (id: string) => ['executions', id, 'logs'] as const,
  executionHookLogs: (id: string) => ['executions', id, 'hook-logs'] as const,
  executionUsage: (id: string) => ['executions', id, 'usage'] as const,
  taskUsage: (taskId: string) => ['tasks', taskId, 'usage'] as const,
  agentDiscoveredOptions: (id: string) => ['agents', id, 'discovered-options'] as const,
  executorDiscoveredOptions: (executorType: string) =>
    ['executor-types', executorType, 'discovered-options'] as const,
  agentAvailability: (id: string) => ['agents', id, 'availability'] as const,
  executorTypes: ['executor-types'] as const,
  daemons: ['daemons'] as const,
  clis: ['clis'] as const,
  workflow: (projectId: string) => ['projects', projectId, 'workflow'] as const,
  workflowPromptBuilders: ['workflow', 'prompt-builders'] as const,
  transitions: (taskId: string) => ['tasks', taskId, 'transitions'] as const,
  taskRoles: (taskId: string) => ['tasks', taskId, 'roles'] as const,
  taskWorkspace: (taskId: string) => ['tasks', taskId, 'workspace'] as const,
  taskExternalLinks: (taskId: string) => ['tasks', taskId, 'external-links'] as const,
  workflowTemplates: ['workflow-templates'] as const,
  workflowTemplate: (name: string) => ['workflow-templates', name] as const,
  projectAnalytics: (projectId: string, from?: string, to?: string) =>
    ['projects', projectId, 'analytics', from ?? 'all', to ?? 'all'] as const,
  notifications: (projectId?: string, read?: boolean) =>
    ['notifications', projectId ?? 'all', read ?? 'all'] as const,
  notificationUnreadCount: (projectId?: string) =>
    ['notifications', 'unread-count', projectId ?? 'all'] as const,
  operationsStatus: ['operations', 'status'] as const,
  settings: ['settings'] as const,
  integration: (projectId: string) => ['projects', projectId, 'integration'] as const,
  taskDependencies: (taskId: string) => ['tasks', taskId, 'dependencies'] as const,
  taskDependents: (taskId: string) => ['tasks', taskId, 'dependents'] as const,
  pats: () => ['pats'] as const,
  projectMembers: (projectId: string) => ['projects', projectId, 'members'] as const,
  projectAgents: (projectId: string) => ['projects', projectId, 'agents'] as const,
}
